2024-02-23 16:47:21,783 INFO    StreamThr :9296 [internal.py:wandb_internal():86] W&B internal server running at pid: 9296, started at: 2024-02-23 16:47:21.783041
2024-02-23 16:47:21,786 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status
2024-02-23 16:47:21,845 INFO    WriterThread:9296 [datastore.py:open_for_write():87] open: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\run-93ao185l.wandb
2024-02-23 16:47:21,846 DEBUG   SenderThread:9296 [sender.py:send():382] send: header
2024-02-23 16:47:21,846 DEBUG   SenderThread:9296 [sender.py:send():382] send: run
2024-02-23 16:47:23,664 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: check_version
2024-02-23 16:47:23,750 INFO    SenderThread:9296 [dir_watcher.py:__init__():211] watching files in: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files
2024-02-23 16:47:23,750 INFO    SenderThread:9296 [sender.py:_start_run_threads():1136] run started: 93ao185l with start time 1708678041.799038
2024-02-23 16:47:23,750 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: check_version
2024-02-23 16:47:24,293 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: run_start
2024-02-23 16:47:24,338 DEBUG   HandlerThread:9296 [system_info.py:__init__():27] System info init
2024-02-23 16:47:24,338 DEBUG   HandlerThread:9296 [system_info.py:__init__():42] System info init done
2024-02-23 16:47:24,338 INFO    HandlerThread:9296 [system_monitor.py:start():194] Starting system monitor
2024-02-23 16:47:24,338 INFO    SystemMonitor:9296 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-02-23 16:47:24,338 INFO    HandlerThread:9296 [system_monitor.py:probe():214] Collecting system info
2024-02-23 16:47:24,344 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started cpu monitoring
2024-02-23 16:47:24,345 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started disk monitoring
2024-02-23 16:47:24,346 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started gpu monitoring
2024-02-23 16:47:24,346 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started memory monitoring
2024-02-23 16:47:24,356 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started network monitoring
2024-02-23 16:47:24,374 DEBUG   HandlerThread:9296 [system_info.py:probe():151] Probing system
2024-02-23 16:47:24,375 DEBUG   HandlerThread:9296 [gitlib.py:_init_repo():56] git repository is invalid
2024-02-23 16:47:24,375 DEBUG   HandlerThread:9296 [system_info.py:probe():199] Probing system done
2024-02-23 16:47:24,376 DEBUG   HandlerThread:9296 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.11.5', 'heartbeatAt': '2024-02-23T08:47:24.374169', 'startedAt': '2024-02-23T08:47:21.659136', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'depressive_speech.ipynb', 'codePathLocal': 'depressive_speech.ipynb', 'root': 'D:\\Paper\\red-flag-text-detection-main', 'host': 'LAPTOP-98MBCKEB', 'username': 'lenovo', 'executable': 'D:\\Anaconda\\python.exe', 'cpu_count': 4, 'cpu_count_logical': 8, 'cpu_freq': {'current': 2400.0, 'min': 0.0, 'max': 2400.0}, 'cpu_freq_per_core': [{'current': 2400.0, 'min': 0.0, 'max': 2400.0}], 'disk': {'/': {'total': 292.96874618530273, 'used': 71.48701858520508}}, 'gpu': 'NVIDIA GeForce GTX 1650 Ti', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce GTX 1650 Ti', 'memory_total': 4294967296}], 'memory': {'total': 15.909957885742188}}
2024-02-23 16:47:24,376 INFO    HandlerThread:9296 [system_monitor.py:probe():224] Finished collecting system info
2024-02-23 16:47:24,376 INFO    HandlerThread:9296 [system_monitor.py:probe():227] Publishing system info
2024-02-23 16:47:24,376 DEBUG   HandlerThread:9296 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-02-23 16:47:24,387 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:47:24,756 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\conda-environment.yaml
2024-02-23 16:47:26,415 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:47:28,444 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:47:30,473 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:47:32,504 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:47:34,528 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:47:36,558 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:47:38,579 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:47:40,602 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:47:42,630 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:47:44,660 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:47:46,687 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:47:46,919 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\conda-environment.yaml
2024-02-23 16:47:47,046 DEBUG   HandlerThread:9296 [system_info.py:_save_conda():220] Saving conda packages done
2024-02-23 16:47:47,047 INFO    HandlerThread:9296 [system_monitor.py:probe():229] Finished publishing system info
2024-02-23 16:47:47,127 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:47:47,127 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: keepalive
2024-02-23 16:47:47,127 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:47:47,127 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: keepalive
2024-02-23 16:47:47,127 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:47:47,128 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: keepalive
2024-02-23 16:47:47,128 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:47:47,128 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: keepalive
2024-02-23 16:47:47,128 DEBUG   SenderThread:9296 [sender.py:send():382] send: files
2024-02-23 16:47:47,128 INFO    SenderThread:9296 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-02-23 16:47:47,142 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: python_packages
2024-02-23 16:47:47,142 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: python_packages
2024-02-23 16:47:47,142 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:47:47,143 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:47:47,145 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:47:47,936 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\wandb-metadata.json
2024-02-23 16:47:47,936 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\requirements.txt
2024-02-23 16:47:48,372 DEBUG   SenderThread:9296 [sender.py:send():382] send: telemetry
2024-02-23 16:47:48,372 DEBUG   SenderThread:9296 [sender.py:send():382] send: config
2024-02-23 16:47:48,373 DEBUG   SenderThread:9296 [sender.py:send():382] send: metric
2024-02-23 16:47:48,373 DEBUG   SenderThread:9296 [sender.py:send():382] send: telemetry
2024-02-23 16:47:48,373 DEBUG   SenderThread:9296 [sender.py:send():382] send: metric
2024-02-23 16:47:48,374 WARNING SenderThread:9296 [sender.py:send_metric():1354] Seen metric with glob (shouldn't happen)
2024-02-23 16:47:48,374 DEBUG   SenderThread:9296 [sender.py:send():382] send: telemetry
2024-02-23 16:47:48,379 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:47:48,707 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:47:48,855 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002ACDE170A90>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
2024-02-23 16:47:48,855 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1194'}
2024-02-23 16:47:48,855 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-23 16:47:50,017 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002ACDE14AD10>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
2024-02-23 16:47:50,017 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1194'}
2024-02-23 16:47:50,017 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-23 16:47:50,731 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:47:52,129 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002ACDE16B550>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
2024-02-23 16:47:52,129 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1194'}
2024-02-23 16:47:52,129 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-23 16:47:52,130 INFO    wandb-upload_0:9296 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "D:\Anaconda\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\Lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "D:\Anaconda\Lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "D:\Anaconda\Lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002ACDE16B550>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002ACDE16B550>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002ACDE16B550>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "D:\Anaconda\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-02-23 16:47:52,764 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:47:53,410 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:47:54,821 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:47:55,982 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\config.yaml
2024-02-23 16:47:56,838 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:47:57,216 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002ACDE777250>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
2024-02-23 16:47:57,216 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1194'}
2024-02-23 16:47:57,216 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-23 16:47:58,856 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:48:00,241 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:48:00,881 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:48:02,148 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:48:02,225 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:48:02,225 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:48:02,257 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: pause
2024-02-23 16:48:02,257 INFO    HandlerThread:9296 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-02-23 16:48:02,257 INFO    HandlerThread:9296 [system_monitor.py:finish():203] Stopping system monitor
2024-02-23 16:48:02,257 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-02-23 16:48:02,258 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-02-23 16:48:02,258 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-02-23 16:48:02,258 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined cpu monitor
2024-02-23 16:48:02,266 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined disk monitor
2024-02-23 16:48:02,296 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined gpu monitor
2024-02-23 16:48:02,296 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined memory monitor
2024-02-23 16:48:02,296 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined network monitor
2024-02-23 16:48:02,683 DEBUG   SenderThread:9296 [sender.py:send():382] send: stats
2024-02-23 16:48:03,044 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\output.log
2024-02-23 16:48:05,057 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\output.log
2024-02-23 16:48:05,728 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:48:06,678 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002ACDE776B50>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
2024-02-23 16:48:06,678 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1194'}
2024-02-23 16:48:06,678 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-23 16:48:10,760 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:48:15,802 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:48:17,150 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:48:17,182 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:48:17,182 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:48:21,715 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:48:24,601 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002ACDE799A50>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
2024-02-23 16:48:24,601 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1194'}
2024-02-23 16:48:24,601 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-23 16:48:26,762 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:48:31,803 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:48:32,163 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:48:32,194 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:48:32,194 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:48:37,463 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:48:42,503 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:48:47,173 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:48:47,203 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:48:47,204 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:48:48,352 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:48:53,385 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:48:58,423 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:49:02,182 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:49:02,197 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:49:02,197 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:49:03,681 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:49:03,948 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002ACDE16B710>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
2024-02-23 16:49:03,948 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1194'}
2024-02-23 16:49:03,948 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-23 16:49:08,719 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:49:13,764 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:49:17,185 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:49:17,216 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:49:17,216 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:49:19,654 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:49:24,696 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:49:29,745 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:49:32,197 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:49:32,212 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:49:32,213 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:49:34,651 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: resume
2024-02-23 16:49:34,651 INFO    HandlerThread:9296 [handler.py:handle_request_resume():699] starting system metrics thread
2024-02-23 16:49:34,651 INFO    HandlerThread:9296 [system_monitor.py:start():194] Starting system monitor
2024-02-23 16:49:34,651 INFO    SystemMonitor:9296 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-02-23 16:49:34,656 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started cpu monitoring
2024-02-23 16:49:34,656 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started disk monitoring
2024-02-23 16:49:34,657 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started gpu monitoring
2024-02-23 16:49:34,658 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started memory monitoring
2024-02-23 16:49:34,682 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started network monitoring
2024-02-23 16:49:34,691 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:49:34,754 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: pause
2024-02-23 16:49:34,754 INFO    HandlerThread:9296 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-02-23 16:49:34,754 INFO    HandlerThread:9296 [system_monitor.py:finish():203] Stopping system monitor
2024-02-23 16:49:34,754 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-02-23 16:49:34,755 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-02-23 16:49:34,755 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-02-23 16:49:34,755 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined cpu monitor
2024-02-23 16:49:34,762 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined disk monitor
2024-02-23 16:49:34,794 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined gpu monitor
2024-02-23 16:49:34,794 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined memory monitor
2024-02-23 16:49:34,794 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined network monitor
2024-02-23 16:49:34,795 DEBUG   SenderThread:9296 [sender.py:send():382] send: stats
2024-02-23 16:49:34,796 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:49:37,812 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\output.log
2024-02-23 16:49:39,855 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:49:44,894 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:49:47,200 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:49:47,215 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:49:47,215 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:49:50,636 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:49:55,669 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:50:00,731 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:50:02,210 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:50:02,225 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:50:02,225 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:50:06,680 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:50:10,683 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002ACDE79BCD0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
2024-02-23 16:50:10,683 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1194'}
2024-02-23 16:50:10,683 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-23 16:50:11,707 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:50:16,750 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:50:17,218 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:50:17,248 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:50:17,248 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:50:22,696 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:50:27,741 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:50:32,219 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:50:32,251 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:50:32,251 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:50:32,747 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:50:34,287 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: resume
2024-02-23 16:50:34,287 INFO    HandlerThread:9296 [handler.py:handle_request_resume():699] starting system metrics thread
2024-02-23 16:50:34,287 INFO    HandlerThread:9296 [system_monitor.py:start():194] Starting system monitor
2024-02-23 16:50:34,287 INFO    SystemMonitor:9296 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-02-23 16:50:34,291 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started cpu monitoring
2024-02-23 16:50:34,292 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started disk monitoring
2024-02-23 16:50:34,292 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started gpu monitoring
2024-02-23 16:50:34,293 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started memory monitoring
2024-02-23 16:50:34,313 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started network monitoring
2024-02-23 16:50:34,322 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:50:34,365 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: pause
2024-02-23 16:50:34,365 INFO    HandlerThread:9296 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-02-23 16:50:34,365 INFO    HandlerThread:9296 [system_monitor.py:finish():203] Stopping system monitor
2024-02-23 16:50:34,366 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined cpu monitor
2024-02-23 16:50:34,366 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined disk monitor
2024-02-23 16:50:34,366 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-02-23 16:50:34,373 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-02-23 16:50:34,373 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-02-23 16:50:34,408 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined gpu monitor
2024-02-23 16:50:34,408 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined memory monitor
2024-02-23 16:50:34,409 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined network monitor
2024-02-23 16:50:34,409 DEBUG   SenderThread:9296 [sender.py:send():382] send: stats
2024-02-23 16:50:35,288 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\output.log
2024-02-23 16:50:38,432 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:50:39,662 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: resume
2024-02-23 16:50:39,662 INFO    HandlerThread:9296 [handler.py:handle_request_resume():699] starting system metrics thread
2024-02-23 16:50:39,662 INFO    HandlerThread:9296 [system_monitor.py:start():194] Starting system monitor
2024-02-23 16:50:39,663 INFO    SystemMonitor:9296 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-02-23 16:50:39,668 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started cpu monitoring
2024-02-23 16:50:39,669 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started disk monitoring
2024-02-23 16:50:39,670 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started gpu monitoring
2024-02-23 16:50:39,670 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started memory monitoring
2024-02-23 16:50:39,695 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started network monitoring
2024-02-23 16:50:39,706 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:50:39,774 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: pause
2024-02-23 16:50:39,774 INFO    HandlerThread:9296 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-02-23 16:50:39,774 INFO    HandlerThread:9296 [system_monitor.py:finish():203] Stopping system monitor
2024-02-23 16:50:39,774 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-02-23 16:50:39,775 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-02-23 16:50:39,781 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-02-23 16:50:39,781 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined cpu monitor
2024-02-23 16:50:39,782 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined disk monitor
2024-02-23 16:50:39,813 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined gpu monitor
2024-02-23 16:50:39,813 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined memory monitor
2024-02-23 16:50:39,813 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined network monitor
2024-02-23 16:50:39,813 DEBUG   SenderThread:9296 [sender.py:send():382] send: stats
2024-02-23 16:50:41,399 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\output.log
2024-02-23 16:50:43,963 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:50:45,993 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: resume
2024-02-23 16:50:45,993 INFO    HandlerThread:9296 [handler.py:handle_request_resume():699] starting system metrics thread
2024-02-23 16:50:45,993 INFO    HandlerThread:9296 [system_monitor.py:start():194] Starting system monitor
2024-02-23 16:50:45,994 INFO    SystemMonitor:9296 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-02-23 16:50:45,998 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started cpu monitoring
2024-02-23 16:50:45,999 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started disk monitoring
2024-02-23 16:50:46,000 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started gpu monitoring
2024-02-23 16:50:46,000 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started memory monitoring
2024-02-23 16:50:46,021 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started network monitoring
2024-02-23 16:50:46,046 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:50:46,099 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: pause
2024-02-23 16:50:46,099 INFO    HandlerThread:9296 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-02-23 16:50:46,099 INFO    HandlerThread:9296 [system_monitor.py:finish():203] Stopping system monitor
2024-02-23 16:50:46,099 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-02-23 16:50:46,100 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-02-23 16:50:46,100 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined cpu monitor
2024-02-23 16:50:46,100 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-02-23 16:50:46,107 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined disk monitor
2024-02-23 16:50:46,139 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined gpu monitor
2024-02-23 16:50:46,139 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined memory monitor
2024-02-23 16:50:46,139 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined network monitor
2024-02-23 16:50:46,139 DEBUG   SenderThread:9296 [sender.py:send():382] send: stats
2024-02-23 16:50:47,225 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:50:47,256 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:50:47,257 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:50:47,458 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\output.log
2024-02-23 16:50:49,716 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:50:54,759 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:50:59,798 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:51:02,227 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:51:02,273 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:51:02,274 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:51:05,421 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:51:10,464 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:51:15,498 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:51:17,237 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:51:17,285 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:51:17,285 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:51:20,762 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:51:21,287 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: resume
2024-02-23 16:51:21,287 INFO    HandlerThread:9296 [handler.py:handle_request_resume():699] starting system metrics thread
2024-02-23 16:51:21,287 INFO    HandlerThread:9296 [system_monitor.py:start():194] Starting system monitor
2024-02-23 16:51:21,288 INFO    SystemMonitor:9296 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-02-23 16:51:21,293 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started cpu monitoring
2024-02-23 16:51:21,293 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started disk monitoring
2024-02-23 16:51:21,294 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started gpu monitoring
2024-02-23 16:51:21,295 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started memory monitoring
2024-02-23 16:51:21,316 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started network monitoring
2024-02-23 16:51:21,327 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:51:21,388 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: pause
2024-02-23 16:51:21,388 INFO    HandlerThread:9296 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-02-23 16:51:21,388 INFO    HandlerThread:9296 [system_monitor.py:finish():203] Stopping system monitor
2024-02-23 16:51:21,388 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-02-23 16:51:21,389 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined cpu monitor
2024-02-23 16:51:21,394 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-02-23 16:51:21,395 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined disk monitor
2024-02-23 16:51:21,395 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-02-23 16:51:21,426 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined gpu monitor
2024-02-23 16:51:21,426 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined memory monitor
2024-02-23 16:51:21,427 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined network monitor
2024-02-23 16:51:21,427 DEBUG   SenderThread:9296 [sender.py:send():382] send: stats
2024-02-23 16:51:23,778 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\output.log
2024-02-23 16:51:26,462 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:51:31,495 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:51:32,240 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:51:32,303 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:51:32,303 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:51:36,723 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:51:40,213 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: resume
2024-02-23 16:51:40,213 INFO    HandlerThread:9296 [handler.py:handle_request_resume():699] starting system metrics thread
2024-02-23 16:51:40,213 INFO    HandlerThread:9296 [system_monitor.py:start():194] Starting system monitor
2024-02-23 16:51:40,213 INFO    SystemMonitor:9296 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-02-23 16:51:40,218 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started cpu monitoring
2024-02-23 16:51:40,218 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: pause
2024-02-23 16:51:40,219 INFO    HandlerThread:9296 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-02-23 16:51:40,219 INFO    HandlerThread:9296 [system_monitor.py:finish():203] Stopping system monitor
2024-02-23 16:51:40,219 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started disk monitoring
2024-02-23 16:51:40,219 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-02-23 16:51:40,219 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined cpu monitor
2024-02-23 16:51:40,219 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-02-23 16:51:40,220 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-02-23 16:51:40,220 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined disk monitor
2024-02-23 16:51:40,220 DEBUG   SenderThread:9296 [sender.py:send():382] send: stats
2024-02-23 16:51:40,933 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\output.log
2024-02-23 16:51:42,256 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:51:47,253 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:51:47,298 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:51:47,329 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:51:47,329 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:51:48,887 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: resume
2024-02-23 16:51:48,888 INFO    HandlerThread:9296 [handler.py:handle_request_resume():699] starting system metrics thread
2024-02-23 16:51:48,888 INFO    HandlerThread:9296 [system_monitor.py:start():194] Starting system monitor
2024-02-23 16:51:48,888 INFO    SystemMonitor:9296 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-02-23 16:51:48,893 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started cpu monitoring
2024-02-23 16:51:48,894 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started disk monitoring
2024-02-23 16:51:48,895 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started gpu monitoring
2024-02-23 16:51:48,895 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started memory monitoring
2024-02-23 16:51:48,907 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started network monitoring
2024-02-23 16:51:48,923 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:51:48,994 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: pause
2024-02-23 16:51:48,994 INFO    HandlerThread:9296 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-02-23 16:51:48,994 INFO    HandlerThread:9296 [system_monitor.py:finish():203] Stopping system monitor
2024-02-23 16:51:48,994 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined cpu monitor
2024-02-23 16:51:48,994 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-02-23 16:51:49,000 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined disk monitor
2024-02-23 16:51:49,000 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-02-23 16:51:49,001 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-02-23 16:51:49,032 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined gpu monitor
2024-02-23 16:51:49,033 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined memory monitor
2024-02-23 16:51:49,033 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined network monitor
2024-02-23 16:51:49,033 DEBUG   SenderThread:9296 [sender.py:send():382] send: stats
2024-02-23 16:51:51,140 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\output.log
2024-02-23 16:51:53,064 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:51:58,244 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:51:58,591 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: resume
2024-02-23 16:51:58,591 INFO    HandlerThread:9296 [handler.py:handle_request_resume():699] starting system metrics thread
2024-02-23 16:51:58,591 INFO    HandlerThread:9296 [system_monitor.py:start():194] Starting system monitor
2024-02-23 16:51:58,592 INFO    SystemMonitor:9296 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-02-23 16:51:58,599 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started cpu monitoring
2024-02-23 16:51:58,600 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started disk monitoring
2024-02-23 16:51:58,601 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started gpu monitoring
2024-02-23 16:51:58,601 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started memory monitoring
2024-02-23 16:51:58,621 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started network monitoring
2024-02-23 16:51:58,645 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:51:58,699 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: pause
2024-02-23 16:51:58,700 INFO    HandlerThread:9296 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-02-23 16:51:58,700 INFO    HandlerThread:9296 [system_monitor.py:finish():203] Stopping system monitor
2024-02-23 16:51:58,700 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined cpu monitor
2024-02-23 16:51:58,701 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined disk monitor
2024-02-23 16:51:58,701 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-02-23 16:51:58,707 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-02-23 16:51:58,707 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-02-23 16:51:58,743 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined gpu monitor
2024-02-23 16:51:58,743 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined memory monitor
2024-02-23 16:51:58,743 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined network monitor
2024-02-23 16:51:58,744 DEBUG   SenderThread:9296 [sender.py:send():382] send: stats
2024-02-23 16:51:59,276 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\output.log
2024-02-23 16:52:02,251 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:52:02,329 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:52:02,330 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:52:03,834 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:52:05,736 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: resume
2024-02-23 16:52:05,736 INFO    HandlerThread:9296 [handler.py:handle_request_resume():699] starting system metrics thread
2024-02-23 16:52:05,736 INFO    HandlerThread:9296 [system_monitor.py:start():194] Starting system monitor
2024-02-23 16:52:05,737 INFO    SystemMonitor:9296 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-02-23 16:52:05,741 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started cpu monitoring
2024-02-23 16:52:05,742 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started disk monitoring
2024-02-23 16:52:05,742 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started gpu monitoring
2024-02-23 16:52:05,743 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started memory monitoring
2024-02-23 16:52:05,763 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started network monitoring
2024-02-23 16:52:05,773 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:52:05,838 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: pause
2024-02-23 16:52:05,839 INFO    HandlerThread:9296 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-02-23 16:52:05,839 INFO    HandlerThread:9296 [system_monitor.py:finish():203] Stopping system monitor
2024-02-23 16:52:05,840 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-02-23 16:52:05,845 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-02-23 16:52:05,845 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-02-23 16:52:05,846 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined cpu monitor
2024-02-23 16:52:05,846 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined disk monitor
2024-02-23 16:52:05,877 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined gpu monitor
2024-02-23 16:52:05,877 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined memory monitor
2024-02-23 16:52:05,877 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined network monitor
2024-02-23 16:52:05,975 DEBUG   SenderThread:9296 [sender.py:send():382] send: stats
2024-02-23 16:52:07,369 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\output.log
2024-02-23 16:52:08,997 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:52:14,036 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:52:17,254 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:52:17,331 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:52:17,331 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:52:19,913 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:52:24,963 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:52:29,993 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:52:32,266 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:52:32,330 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:52:32,330 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:52:35,794 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:52:40,846 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:52:40,897 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002ACDE0DB350>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
2024-02-23 16:52:40,898 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1194'}
2024-02-23 16:52:40,898 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-23 16:52:45,885 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:52:47,269 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:52:47,331 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:52:47,331 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:52:51,795 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:52:56,849 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:53:01,902 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:53:02,275 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:53:02,337 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:53:02,337 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:53:07,905 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:53:12,963 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:53:17,275 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:53:17,355 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:53:17,356 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:53:18,793 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:53:23,831 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:53:28,879 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:53:32,290 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:53:32,352 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:53:32,353 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:53:34,827 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:53:39,879 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:53:44,914 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:53:47,296 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:53:47,358 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:53:47,358 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:53:50,462 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:53:55,504 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:54:00,554 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:54:02,306 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:54:02,368 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:54:02,369 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:54:05,898 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:54:10,962 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:54:16,008 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:54:17,308 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:54:17,385 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:54:17,385 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:54:21,921 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:54:26,954 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:54:31,998 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:54:32,309 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:54:32,388 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:54:32,388 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:54:37,973 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:54:43,016 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:54:47,317 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:54:47,394 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:54:47,395 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:54:48,923 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:54:53,970 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:54:59,030 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:55:02,324 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:55:02,401 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:55:02,402 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:55:04,981 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:55:10,030 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:55:15,237 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:55:17,356 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:55:17,401 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:55:17,401 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:55:20,941 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:55:25,992 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:55:31,032 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:55:32,371 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:55:32,403 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:55:32,403 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:55:36,889 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:55:41,927 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:55:46,977 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:55:47,385 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:55:47,401 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:55:47,401 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:55:52,390 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:55:57,435 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:56:02,401 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:56:02,416 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:56:02,416 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:56:02,943 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:56:07,997 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:56:13,059 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:56:17,410 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:56:17,425 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:56:17,426 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:56:18,877 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:56:23,906 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:56:28,944 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:56:32,421 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:56:32,422 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:56:32,422 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:56:33,955 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:56:38,989 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:56:44,058 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:56:47,425 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:56:47,426 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:56:47,426 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:56:49,845 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:56:54,880 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:56:59,941 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:57:02,422 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:57:02,422 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:57:02,422 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:57:05,948 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:57:08,704 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: resume
2024-02-23 16:57:08,704 INFO    HandlerThread:9296 [handler.py:handle_request_resume():699] starting system metrics thread
2024-02-23 16:57:08,704 INFO    HandlerThread:9296 [system_monitor.py:start():194] Starting system monitor
2024-02-23 16:57:08,705 INFO    SystemMonitor:9296 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-02-23 16:57:08,710 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started cpu monitoring
2024-02-23 16:57:08,710 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started disk monitoring
2024-02-23 16:57:08,711 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started gpu monitoring
2024-02-23 16:57:08,711 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started memory monitoring
2024-02-23 16:57:08,732 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started network monitoring
2024-02-23 16:57:08,742 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:57:08,820 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: pause
2024-02-23 16:57:08,820 INFO    HandlerThread:9296 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-02-23 16:57:08,820 INFO    HandlerThread:9296 [system_monitor.py:finish():203] Stopping system monitor
2024-02-23 16:57:08,826 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-02-23 16:57:08,826 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-02-23 16:57:08,826 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined cpu monitor
2024-02-23 16:57:08,826 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-02-23 16:57:08,827 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined disk monitor
2024-02-23 16:57:08,858 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined gpu monitor
2024-02-23 16:57:08,858 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined memory monitor
2024-02-23 16:57:08,858 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined network monitor
2024-02-23 16:57:08,858 DEBUG   SenderThread:9296 [sender.py:send():382] send: stats
2024-02-23 16:57:11,883 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:57:12,009 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\output.log
2024-02-23 16:57:16,920 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:57:17,421 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:57:17,422 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:57:17,437 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:57:21,984 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:57:23,890 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: resume
2024-02-23 16:57:23,890 INFO    HandlerThread:9296 [handler.py:handle_request_resume():699] starting system metrics thread
2024-02-23 16:57:23,890 INFO    HandlerThread:9296 [system_monitor.py:start():194] Starting system monitor
2024-02-23 16:57:23,890 INFO    SystemMonitor:9296 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-02-23 16:57:23,895 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started cpu monitoring
2024-02-23 16:57:23,896 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started disk monitoring
2024-02-23 16:57:23,897 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started gpu monitoring
2024-02-23 16:57:23,897 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started memory monitoring
2024-02-23 16:57:23,919 INFO    SystemMonitor:9296 [interfaces.py:start():190] Started network monitoring
2024-02-23 16:57:23,929 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:57:25,963 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:57:27,116 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\output.log
2024-02-23 16:57:27,569 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/idiau/huggingface/93ao185l/wandb-metadata.json?Expires=1708764468&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o%2BngKONqRhdji2q0Dd01OYbqg3cJQf68GKspmUeI57XNo1h76p0KEELaQe0wG6rR7C4JlO6AJ4%2B5%2FQYO09KyhZO3EatQvOAumoXSZ8V1UkVjfHhrACaRM6qid8RQ2dR%2FQMDKRVnbiQLBudZ3JOKfaYRf1TQPGDyo0UpOkXaZI0iHFyOcnDWqkQq64ZZcWXF4px7nspBwSY%2Fw8hXDfcEtkJVindo%2FVAemAYKYLwsoj0EYP52qqvsoAd2etax6pofgwgq%2BDJGEBhEJYvOExWrTFMV4fvL%2BhtMGtg2hiahrjglpbxTalBzc1GmFdUj7%2BkOtd%2BpiOTC%2FNwGvLwusSwx88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002ACDE7A4690>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
2024-02-23 16:57:27,569 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1194'}
2024-02-23 16:57:27,569 ERROR   wandb-upload_0:9296 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-23 16:57:27,922 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:57:27,999 ERROR   gpu       :9296 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-02-23 16:57:29,713 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: pause
2024-02-23 16:57:29,713 INFO    HandlerThread:9296 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-02-23 16:57:29,713 INFO    HandlerThread:9296 [system_monitor.py:finish():203] Stopping system monitor
2024-02-23 16:57:29,714 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-02-23 16:57:29,714 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined cpu monitor
2024-02-23 16:57:29,719 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-02-23 16:57:29,719 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined disk monitor
2024-02-23 16:57:29,719 DEBUG   SystemMonitor:9296 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-02-23 16:57:29,752 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined gpu monitor
2024-02-23 16:57:29,752 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined memory monitor
2024-02-23 16:57:29,752 INFO    HandlerThread:9296 [interfaces.py:finish():202] Joined network monitor
2024-02-23 16:57:29,753 DEBUG   SenderThread:9296 [sender.py:send():382] send: stats
2024-02-23 16:57:32,140 INFO    Thread-16 :9296 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\output.log
2024-02-23 16:57:32,433 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:57:32,433 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:57:32,450 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:57:33,896 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:57:38,947 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:57:43,999 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:57:47,443 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:57:47,443 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:57:47,458 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:57:49,150 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:57:54,177 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:57:59,222 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:58:02,451 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: stop_status
2024-02-23 16:58:02,451 DEBUG   SenderThread:9296 [sender.py:send_request():409] send_request: stop_status
2024-02-23 16:58:02,467 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-23 16:58:04,961 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:58:10,001 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:58:15,023 DEBUG   HandlerThread:9296 [handler.py:handle_request():146] handle_request: status_report
2024-02-23 16:58:20,011 WARNING StreamThr :9296 [internal.py:is_dead():414] Internal process exiting, parent pid 17808 disappeared
2024-02-23 16:58:20,011 ERROR   StreamThr :9296 [internal.py:wandb_internal():152] Internal process shutdown.
2024-02-23 16:58:20,058 INFO    SenderThread:9296 [sender.py:finish():1572] shutting down sender
2024-02-23 16:58:20,058 INFO    WriterThread:9296 [datastore.py:close():296] close: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\run-93ao185l.wandb
2024-02-23 16:58:20,058 INFO    HandlerThread:9296 [handler.py:finish():869] shutting down handler
2024-02-23 16:58:22,907 INFO    SenderThread:9296 [dir_watcher.py:finish():358] shutting down directory watcher
2024-02-23 16:58:23,506 INFO    SenderThread:9296 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\output.log
2024-02-23 16:58:23,506 INFO    SenderThread:9296 [dir_watcher.py:finish():388] scan: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files
2024-02-23 16:58:23,507 INFO    SenderThread:9296 [dir_watcher.py:finish():402] scan save: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\conda-environment.yaml conda-environment.yaml
2024-02-23 16:58:23,507 INFO    SenderThread:9296 [dir_watcher.py:finish():402] scan save: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\config.yaml config.yaml
2024-02-23 16:58:23,519 INFO    SenderThread:9296 [dir_watcher.py:finish():402] scan save: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\output.log output.log
2024-02-23 16:58:23,528 INFO    SenderThread:9296 [dir_watcher.py:finish():402] scan save: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\requirements.txt requirements.txt
2024-02-23 16:58:23,528 INFO    SenderThread:9296 [dir_watcher.py:finish():402] scan save: D:\Paper\red-flag-text-detection-main\wandb\run-20240223_164721-93ao185l\files\wandb-metadata.json wandb-metadata.json
2024-02-23 16:58:23,528 INFO    SenderThread:9296 [file_pusher.py:finish():175] shutting down file pusher
2024-02-23 16:58:23,528 INFO    SenderThread:9296 [file_pusher.py:join():181] waiting for file pusher
2024-02-23 16:58:24,067 INFO    SenderThread:9296 [file_stream.py:finish():595] file stream finish called
2024-02-23 16:58:24,455 INFO    SenderThread:9296 [file_stream.py:finish():599] file stream finish is done
